name: dev_garage
description: "A Dev's Garage"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shadcn_ui: ^0.15.4
  jayse: ^0.0.5-beta
  shared_preferences: ^2.3.3
  beamer: ^1.7.0
  arborio: ^0.3.0-beta
  signals: ^6.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter:

  uses-material-design: true
