name: dev_garage
description: "A Dev's Garage"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shadcn_ui: ^0.13.4+1

  drift: ^2.21.0
  drift_flutter: ^0.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.21.0
  build_runner: ^2.4.13

flutter:

  uses-material-design: true
